vim.schedule(function()
    vim.lsp.enable({
        "vtsls",
        "biome",
        "lua-language-server",
        "json-language-server",
        "tinymist",
        "astro-language-server",
        "dprint",
    })
end)
